# Generated by Django 5.1.3 on 2024-12-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_token',
        ),
    ]
