# Generated by Django 5.1.3 on 2024-11-29 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_IMAGES/')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publilished')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
